name: 'file creation'
description: 'create file'
inputs:
  mail:
    description: 'mail'
    required: true
  name:
    description: 'name'
    required: true
  phone:
    description: 'phone'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install (make4ht) texlive-extra-utils
      shell: bash
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update
        sudo apt-get install -y texlive-extra-utils texlive-latex-extra texlive-lang-french

    - name: Create html css
      shell: bash
      env:
        MAIL: ${{ inputs.mail }}
        NAME: ${{ inputs.name }}
        PHONE: ${{ inputs.phone }}
      run: |
        chmod +x ./CLI_html_css_creation.sh
        ./CLI_html_css_creation.sh cv.tex
