name: 'file creation'
description: 'create file'
inputs:
  fmail:
    description: 'fMail'
    required: true
  fname:
    description: 'fName'
    required: true
  fphone:
    description: 'fPhone'
    required: true
  mail:
    description: 'mail'
    required: true
  name:
    description: 'name'
    required: true
  phone:
    description: 'phone'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install (make4ht) texlive-extra-utils
      shell: bash
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update
        sudo apt-get install -y texlive-extra-utils texlive-latex-extra texlive-lang-french

    - name: Create html css
      shell: bash
      env:
        MAIL: ${{ inputs.fMail }}
        NAME: ${{ inputs.fName }}
        PHONE: ${{ inputs.fPhone }}
      run: |
        chmod +x ./CLI_html_css_creation.sh
        ./CLI_html_css_creation.sh cv.tex

    - name: Create pdf
      shell: bash
      env:
        MAIL: ${{ inputs.fName }}
        NAME: ${{ inputs.fMail }}
        PHONE: ${{ inputs.fPhone }}
      run: |
        chmod +x ./CLI_pdf_creation.sh
        ./CLI_pdf_creation.sh cv.tex
